name: Python Greetings Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  install-pip-deps:
    name: Install Python Dependencies
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Checkout python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Installing all required dependencies...
        run: |
          python3 --version
          pip3 install -r requirements.txt
        working-directory: python-greetings
